### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nferruzzi** [detroit-labs/IRLSize#17]
I've a measure in inch and I want convert it to a frame size; how do I do it ? it's not obvious from the documentation; there is no UnitLength that can be associated to the current device "point" size

```
let desiredWidth = Measurement(value: 10, unit: UnitLength.inches)
let desiredHeight = Measurement(value: 10, unit: UnitLength.inches)

let size = CGSize(width: ??, height: ??)
```

thanks in advance

**Comment by SlaunchaMan** [comment]
The canonical solution for sizing a UIView is to use the `‑irl_transformForPhysicalHeight:` or `‑irl_transformForPhysicalWidth:` methods on `UIView` to obtain a `CGAffineTransform` that will transform your view to the correct size. If you want to specify pixels, you can get the physical measurements of the screen using the `‑irl_physicalScreenHeight` or `irl_physicalScreenWidth` properties on `UIDevice`; divide your desired width or height by the screen’s width or height to obtain a ratio, then multiply that by the screen’s size in pixels.
