### ISSUE TITLE
SDVersion is out of date

### ISSUE THREAD

**Issue by donie-inhance** [detroit-labs/IRLSize#21]
Would it be possible to add the content of SDVersion to your library as the dependency to that pod is useless unless it's maintained.

It has not been updated for the latest iPhones.

**Comment by SlaunchaMan** [comment]
I'm actually working on a new library that would replace SDVersion as a dependency here. It’s not quite ready yet, but at least for now all screen sizes should still work. I’m hoping to get the replacement out before the next batch of iPhones is announced.

**Comment by donie-inhance** [comment]
Hi Jeff

Thanks for responding...

But SDVersion doesn’t appear to have the new iPhones like XS etc? Just wondering what you mean by getting it out before the next batch of phones are announced? 

Donie

**Comment by SlaunchaMan** [comment]
Right—but IRLSize estimates size based on screen points. It’s not perfect, especially for people using zoomed displays, but it’s better than nothing. So, an iPhone XS Max will have the correct size in IRLSize.

**Comment by SlaunchaMan** [comment]
SDVersion has been replaced with [Orchard](https://github.com/SlaunchaMan/Orchard), so IRLSize now supports all devices with version 2.2.0.
