### ISSUE TITLE
How to resize a UIImage in mm?

### ISSUE THREAD

**Issue by SatbirTanda** [detroit-labs/IRLSize#23]
Is it possible to apply this framework to a UIImage?  I want to resize an image to 152 mm x 203 mm for printing on paper?

**Comment by SlaunchaMan** [comment]
This framework is focused more on ensuring that the on-screen size is accurate. For printing, you’d probably be best off using a [UIPrintPageRenderer](https://developer.apple.com/documentation/uikit/uiprintpagerenderer) and manually specifying the exact size to draw.

**Comment by SatbirTanda** [comment]
Do you think if I size an imageview to 51x51mm for ex, then set its image, and then snapshot the image view, that it will work? It seems to give the wrong size.  The width and height is 302, 302 - when it is exported out, preview say its 152 mm?
