### ISSUE TITLE
New device support question

### ISSUE THREAD

**Issue by taboulot** [detroit-labs/IRLSize#27]
Hi @SlaunchaMan 👋🏼!

## Context

I'm currently developing an application for medical purpose. I have some screens on which I have to display elements in millimeters regardless the device.

First thanks for your library it really helped me 😁

But I didn't anticipate that your library is based on constant that you have to update every time a new apple device is released.

What I understand is that for doing the conversion from millimeters to points, we need the physical size of the device.

## My Problem

I can't guaranteed to my client that our application will work with future apple devices.
Our release process is very long. For each release, we have to follow a process that can take several days/weeks...
So creating a new release for every new iPhone is a process that we would like to avoid.

## Question

I see that providing the real physical size of a device is not provided in iOS SDK. This is why you have to maintain a list of constant.

Is there a way to do the conversion from millimeters to points without maintaining constants for each device ?
Or are we condemned to deal with this limitation ?

Thanks for your answers and help 😄

**Comment by SlaunchaMan** [comment]
Hi @taboulot! You are correct that new devices may not be supported. In fact, if a new device comes out with the same screen resolution as an older device, we'll estimate its size based on previous devices.

I think the best solution for you would be to maintain a server-side list of device IDs (currently in [Orchard](https://github.com/SlaunchaMan/Orchard)) and physical screen dimensions that you fetch regularly. Then, you can add new devices to it without needing to re-build. That’s not something that IRLSize can do today, and there would have to be a lot of refactoring to achieve it, but I think it’s doable. If you’re interested in going down that road, I will definitely accept PRs!

If you want to develop your own system outside of IRLSize, check out Apple’s [Accessory Design Guidelines for Apple Devices](https://developer.apple.com/accessories/Accessory-Design-Guidelines.pdf). This PDF is regularly updated when new devices come out and is the source of data for IRLSize—specifically, the “display active area” of the devices. Combining that with the device model identifiers—[The iPhone Wiki](https://www.theiphonewiki.com) is a good source for that—you could build an entirely server-driven solution.

**Comment by taboulot** [comment]
Thanks a lot for your help and informations !
